### PR TITLE
refactor: make code cleaner to look at

### PR DESCRIPTION
**Pull request by ishan-chhabra**

### CODE REVIEW

**Comment by ishan-chhabra** [comment]
@sriram-kailasam

**Comment by sriram-kailasam** [comment]
Appreciate the compile time improvement, but there are no unit tests and build is failing. Can't merge.

**Comment by ishan-chhabra** [comment]
No issues man! But you must admit that I made it BLAZING FAST! 🎉

**Comment by sriram-kailasam** [comment]
Sure, keep it up!

**Pull request closed without merging**
